-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 18:17:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PinGiDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PinGiDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PinGiDev` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pingidev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pingidev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pingidev` DEFAULT CHARACTER SET utf8mb4 ;
USE `PinGiDev` ;

-- -----------------------------------------------------
-- Table `PinGiDev`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PinGiDev`.`Status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `pingidev` ;

-- -----------------------------------------------------
-- Table `pingidev`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pingidev`.`Product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `route` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pingidev`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pingidev`.`Rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pingidev`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pingidev`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_rol` INT(11) NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_rol_idx` (`id_rol` ASC),
  INDEX `fk_User_Status1_idx` (`id_status` ASC),
  CONSTRAINT `fk_users_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `pingidev`.`Rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `PinGiDev`.`Status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pingidev`.`Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pingidev`.`Favorites` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_product` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_products_products1_idx` (`id_product` ASC),
  INDEX `fk_users_has_products_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_users_has_products_products1`
    FOREIGN KEY (`id_product`)
    REFERENCES `pingidev`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_products_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `pingidev`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pingidev`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pingidev`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  INDEX `fk_user_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_user_has_product_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_product_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pingidev`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pingidev`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pingidev`.`Actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pingidev`.`Actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pingidev`.`Logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pingidev`.`Logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log_date` VARCHAR(45) NOT NULL,
  `Actions_id` INT NOT NULL,
  `User_id` INT(11) NOT NULL,
  INDEX `fk_Actions_has_User_User1_idx` (`User_id` ASC),
  INDEX `fk_Actions_has_User_Actions1_idx` (`Actions_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Actions_has_User_Actions1`
    FOREIGN KEY (`Actions_id`)
    REFERENCES `pingidev`.`Actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actions_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `pingidev`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO rol (id, rol_name) VALUES (0, 'admin');
INSERT INTO rol (id, rol_name) VALUES (1, 'defaultUser');

INSERT INTO status (id, status_name) VALUES (0, 'activated');
INSERT INTO status (id, status_name) VALUES (1, 'deactivated');


INSERT INTO user (id, user_name, pass, email, id_rol, id_status) VALUES (0, 'jpingil', '12345678', 'jorgepinogil013@gmail.com', 0, 0);